name: GCC Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: gcc main.c -Wall -std=c99 -o minecraft -lm && ./minecraft
